name: CI

on: 
  push:
    branches:
      - main

jobs:

  dispatch:
    runs-on: ubuntu-20.04
    steps:
    - name: Dispatch to CSMI
      run: |
        curl --verbose \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.CR_PAT }}" \
          https://api.github.com/repos/master-csmi/csmi/dispatches \
          -d "{\"event_type\": \"stages-updates\" }" 
